// Auto-generated by witffi. Do not edit.

package zcash.eip681

import androidx.annotation.Keep

// ---- Types ----

typealias U256 = ByteArray

/** A native ETH transfer request. */
@Keep
class NativeRequest(
    /** The schema prefix (e.g. "ethereum"). */
    val schemaPrefix: String,
    /** The chain ID, if specified. */
    val chainId: Long?,
    /** The recipient address (ERC-55 checksummed hex string). */
    val recipientAddress: String,
    /** The value in atomic units (wei), if specified. */
    val valueAtomic: ByteArray?,
    /** The gas limit, if specified. */
    val gasLimit: ByteArray?,
    /** The gas price, if specified. */
    val gasPrice: ByteArray?,
    /** The canonical display string (round-trips through parsing). */
    val display: String,
)

/** An ERC-20 token transfer request. */
@Keep
class Erc20Request(
    /** The chain ID, if specified. */
    val chainId: Long?,
    /** The token contract address (ERC-55 checksummed hex string). */
    val tokenContractAddress: String,
    /** The recipient address. */
    val recipientAddress: String,
    /** The value in atomic token units. */
    val valueAtomic: ByteArray,
    /** The canonical display string. */
    val display: String,
)

/** A parsed EIP-681 transaction request. */
@Keep
sealed class TransactionRequest {
    /** A native ETH transfer. */
    @Keep class Native(val value: NativeRequest) : TransactionRequest()
    /** An ERC-20 token transfer. */
    @Keep class Erc20(val value: Erc20Request) : TransactionRequest()
    /** An unrecognised request (raw URI string preserved). */
    @Keep class Unrecognised(val value: String) : TransactionRequest()
}

typealias U256 = ByteArray

// ---- Backend interface ----

/** Interface defining the Eip681 API contract. */
interface Eip681Backend {
    fun parserParse(input: String): TransactionRequest
    fun functionsU256ToString(input: ByteArray): String
}

// ---- Implementation ----

/** JNI-backed implementation of [Eip681Backend]. */
class Eip681(libraryName: String = "eip681_ffi") : Eip681Backend {
    companion object {
        private var loaded = false

        @Synchronized
        fun loadLibrary(name: String) {
            if (!loaded) {
                System.loadLibrary(name)
                loaded = true
            }
        }

        @JvmStatic private external fun nativeParserParse(input: String): TransactionRequest
        @JvmStatic private external fun nativeFunctionsU256ToString(input: ByteArray): String
    }

    init { loadLibrary(libraryName) }

    override fun parserParse(input: String): TransactionRequest {
        return nativeParserParse(input)
    }

    override fun functionsU256ToString(input: ByteArray): String {
        return nativeFunctionsU256ToString(input)
    }

}
