/* Auto-generated by witffi. Do not edit. */
#pragma once

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#include "witffi_types.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ---- Types ---- */

/* FfiByteSlice and FfiByteBuffer are provided by witffi_types.h */

typedef struct {
    FfiByteBuffer schema_prefix;
    uint64_t* chain_id;
    FfiByteBuffer recipient_address;
    FfiByteBuffer* value_atomic;
    FfiByteBuffer* gas_limit;
    FfiByteBuffer* gas_price;
    FfiByteBuffer display;
} FfiNativeRequest;

typedef struct {
    uint64_t* chain_id;
    FfiByteBuffer token_contract_address;
    FfiByteBuffer recipient_address;
    FfiByteBuffer value_atomic;
    FfiByteBuffer display;
} FfiErc20Request;

typedef enum {
    FFI_TRANSACTION_REQUEST_NATIVE = 0,
    FFI_TRANSACTION_REQUEST_ERC20 = 1,
    FFI_TRANSACTION_REQUEST_UNRECOGNISED = 2,
} FfiTransactionRequestTag;

typedef struct {
    FfiNativeRequest value;
} FfiTransactionRequestNativePayload;

typedef struct {
    FfiErc20Request value;
} FfiTransactionRequestErc20Payload;

typedef struct {
    FfiByteBuffer value;
} FfiTransactionRequestUnrecognisedPayload;

typedef struct {
    FfiTransactionRequestTag tag;
    FfiTransactionRequestNativePayload *native;
    FfiTransactionRequestErc20Payload *erc20;
    FfiTransactionRequestUnrecognisedPayload *unrecognised;
} FfiTransactionRequest;

typedef FfiByteBuffer FfiU256;


/* ---- Functions ---- */

int32_t zcash_eip681_last_error_length(void);
int32_t zcash_eip681_error_message_utf8(char *buf, int32_t len);
void zcash_eip681_clear_last_error(void);

FfiTransactionRequest* zcash_eip681_parser_parse(FfiByteSlice input);
FfiByteBuffer zcash_eip681_functions_u256_to_string(FfiByteSlice input);

/* ---- Free functions ---- */

void zcash_eip681_free_byte_buffer(FfiByteBuffer buf);
void zcash_eip681_free_native_request(FfiNativeRequest *ptr);
void zcash_eip681_free_erc20_request(FfiErc20Request *ptr);
void zcash_eip681_free_transaction_request(FfiTransactionRequest *ptr);

#ifdef __cplusplus
}
#endif
